env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-refresh
  - prettier
  - import
settings:
  import/resolver:
    typescript:
      directory:
        - .
    node:
      extensions:
        - .ts
        - .tsx
        - .js
        - .jsx
      paths:
        - src

rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - .tsx
        - .jsx
        - .js
        - .
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - always
  no-console:
    - error
    - allow: ['error']
  max-len:
    - warn
    - code: 120
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  quote-props:
    - error
    - consistent
  brace-style:
    - error
    - 1tbs
  max-statements-per-line:
    - error
    - max: 1
  jsx-quotes:
    - error
    - prefer-single
  indent:
    - error
    - tab
  no-tabs:
    - error
    - allowIndentationTabs: true
  react/jsx-indent:
    - error
    - tab
  react/react-in-jsx-scope: off
  react/jsx-indent-props:
    - error
    - tab
  prettier/prettier: [
      'warn',
      {
        linebreakStyle: 'unix',
        tabWidth: 2,
        semi: true,
        singleQuote: true,
        useTabs: true,
        noconsole: true,
        printWidth: 100,
        bracketSpacing: true,
        # quoteProps: consistent,
        bracketSameLine: false,
        singleAttributePerLine: true,
        jsxSingleQuote: true,
      },
    ]
  no-use-before-define: [
    "error",
    {
      "variables": false
    }
  ]
  import/no-extraneous-dependencies: [
    error,
    {
      devDependencies: true
    }
  ]
